# Nutzt die Ruby-Version deines Projekts
ARG RUBY_VERSION=3.4.8
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION

# Sorgt dafür, dass der Server von außen erreichbar ist
ENV BINDING="0.0.0.0"