default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ZUGANGSDATEN HIERHER VERSCHOBEN (gilt dann für alle):
  host: <%= ENV["DB_HOST"] %>
  username: btv_app
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: btv_anmeldung_development

test:
  <<: *default
  database: btv_anmeldung_test

production:
  primary: &primary_production
    <<: *default
    database: btv_anmeldung_production
  cache:
    <<: *primary_production
    database: btv_anmeldung_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: btv_anmeldung_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: btv_anmeldung_production_cable
    migrations_paths: db/cable_migrate