# Name der App
service: btv_anmeldung

# GitHub Container Registry
image: noahbaumgartner2/btv_anmeldung

# Dein Infomaniak Server
servers:
  web:
    - 89.47.51.202

# WICHTIG: Hier sagen wir Kamal, dass es sich als 'ubuntu' einloggen soll
ssh:
  user: ubuntu

# SSL (HTTPS) automatisch via Let's Encrypt
proxy:
  ssl: true
  host: btvbern-anmeldung.ch

# Wo das gebaute Docker-Image gespeichert wird
registry:
  server: ghcr.io
  username: noahbaumgartner2
  password:
    - KAMAL_REGISTRY_PASSWORD

# Umgebungsvariablen für die Rails App
env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: btv_anmeldung-db # App nutzt diesen internen Namen
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Zubehör: Unser PostgreSQL Datenbank-Container
accessories:
  db:
    image: postgres:16
    host: 89.47.51.202
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: btv_app
        POSTGRES_DB: btv_anmeldung_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

      # Configure the image builder
builder:
  arch: amd64